### ISSUE TITLE
Annotation instructions for CPH data

### ISSUE THREAD

**Issue by nschneid** [dimsum16/dimsum-data#3]
What were annotators told for the [CPH supersense-labeled tweets](https://github.com/coastalcph/supersense-data-twitter)? I need to give my annotator a policy for various tweet-centric phenomena.

Differences I am noticing between Lowlands and Ritter datasets:
- Lowlands consists mostly of promotional material/shares of other content. Most tweets are short, headline-like, and end with a URL. Ritter data is more conversational.
- URLs, usernames, numbers, etc. are obscured in Lowlands data, but not Ritter data.
- In Lowlands data, numbers at the beginning of a noun phrase are joined to form an MWE.
- In Lowlands data, usernames are supersense-tagged as `PERSON` and URLs as `COMMUNICATION`. They are not supersense-tagged in Ritter. I would argue that it's probably not the best use of annotator time to assign labels that can be applied deterministically, nor is it interesting to give credit for such labels in our evaluation.
- Some Ritter tokens are inexplicably missing supersense labels. E.g. in [ritter-train.tsv](https://github.com/coastalcph/supersense-data-twitter/blob/master/ritter-train.tsv#L5808):
  
  ```
  follow  NN  O
  back    NN  O
  ```

**Comment by nschneid** [comment]
Another thing: In Ritter, URLs are POS-tagged as `X`; in Lowlands they are `PROPN`. `X` is the official answer because [it covers `ADD` = email or web address](http://universaldependencies.github.io/docs/en/pos/all.html#al-en-pos/X). @dirkhovy, do you want to update the original Lowlands data? Or should I make the update when generating the data for annotation, and we'll release it in the updated training data once annotation is done?

**Comment by andersjo** [comment]
Dirk changes URLs from `PROPN` to `X` in the Lowlands data

**Comment by nschneid** [comment]
URLs mapped to POS = `X` and no supersense in a1ce9a7 – 0269fe8
