### ISSUE TITLE
Extra blank lines in dimsum16.train

### ISSUE THREAD

**Issue by nschneid** [dimsum16/dimsum-data#4]
These occur between sentences `lowlands-73` and `lowlands-76` (are 74 and 75 supposed to be there?), as well as before the start of the Reviews data. I removed them manually in 07db7a2 but just wanted to check that these aren't due to a preprocessing bug.

**Comment by andersjo** [comment]
They are due to extra line break in the original data file. Removing them now. Note that sentences > lowlands-73 will be renumbered as the gap will disappear.

**Comment by nschneid** [comment]
Thanks. Still a bunch of line breaks between ritter-787 and the Reviews data.
